# Generated by Django 5.1.6 on 2025-03-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='g_email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='l_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='l_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='l_no',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
