# Generated by Django 5.1.6 on 2025-03-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_disease_alter_user_g_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disease',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='l_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='l_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='l_no',
            field=models.IntegerField(max_length=10),
        ),
    ]
