# Generated by Django 5.1.5 on 2025-05-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_archivedmessbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedmessbill',
            name='year',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='year',
            field=models.IntegerField(max_length=10),
        ),
    ]
