# Generated by Django 5.1.5 on 2025-03-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_constant_extra_grocery_vegetables_delete_messbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='constant',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
