# Generated by Django 5.1.5 on 2025-03-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messbill',
            name='dues',
            field=models.IntegerField(default=0),
        ),
    ]
