# Generated by Django 5.1.5 on 2025-03-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_alter_messbill_dues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messbill',
            name='number_of_days',
            field=models.IntegerField(default=10),
        ),
    ]
