# Generated by Django 5.1.6 on 2025-04-02 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0008_messbill_last_updated_messbillhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messbill',
            name='last_updated',
        ),
        migrations.DeleteModel(
            name='MessBillHistory',
        ),
    ]
