# Generated by Django 5.1.6 on 2025-04-02 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0009_remove_messbill_last_updated_delete_messbillhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messbill',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='MessBillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('sch_no', models.IntegerField()),
                ('category', models.CharField(max_length=15)),
                ('branch', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
                ('number_of_days', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('dues', models.IntegerField()),
                ('recorded_date', models.DateField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
