# Generated by Django 5.1.5 on 2025-04-06 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0010_messbill_last_updated_messbillhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messbill',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='messbill',
            name='s_no',
        ),
        migrations.AddField(
            model_name='messbill',
            name='month_year',
            field=models.CharField(default='2025-04', max_length=7),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('room_number', models.CharField(blank=True, max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MessBillHistory',
        ),
    ]
