# Generated by Django 5.1.5 on 2025-04-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0011_remove_messbill_last_updated_remove_messbill_s_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyMessSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=7)),
                ('total_spent', models.PositiveIntegerField()),
                ('total_days', models.PositiveIntegerField()),
                ('number_of_girls', models.PositiveIntegerField()),
                ('per_day_charge', models.FloatField()),
            ],
        ),
    ]
