# Generated by Django 5.1.6 on 2025-05-01 06:38
# Generated by Django 5.1.5 on 2025-05-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0012_monthlymesssummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messbill',
            name='month_year',
            field=models.CharField(default='2025-05', max_length=7),
        ),
    ]
