# Generated by Django 5.1.6 on 2025-05-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_date_of_action_complaint_date_of_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='solved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
